# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: My Thai Star
  description: Contracts between (Angular2/Xamarin) and (oasp4fn/oasp4j/oasp4net)
  version: "1.0.0"
# the domain of the service
host: localhost:3000
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /getdishes:
    post:
      summary: Show Dishes
      description: TODO
      produces:
        - application/json
      parameters:
        - name: filter
          in: body
          description: TODO
          required: true
          schema:
            $ref = "#/definitions/Filter"
      responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/DishView'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  OrderView:
    type: array
    items:
      $ref: "#/definitions/DishView"
  DishView:
    type: object
    properties:
      orderName:
        type: string
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
      orderDescription:
        type: string
        description: Description of product.
      price:
        type: string
        description: Display name of product.
      image:
        type: string
        description: path to the image of dish
      options:
        type: array
        items:
          $ref: "#/definitions/ExtraView"
      likes:
        type: number
        description: number of likes
      favourite:
        type: boolean
        description: TODO
  ImageView:
    type: object
    properties:
      name:
        type: string
        description: A name that the image has. More informative than a URL or a MIME string
      content:
        type: string
        description: Either the URL where the image is located or the MIME stream that has to be parsed on client-side
      type:
        type: string
        enum: [BINARY,URL]
        description: Describes wether the Image itself is a location (url) or a MIME stream.
      extension:
        type: string
        description: The type of file the Image is (.jpg, .png, ...). Necessary when the MIME stream parsing is required.
  ExtraView:
    type: object
    properties:
      name:
        type: string
        description: The name of the extra ingredient
      price:
        type: number
        description: The price of the extra ingredient
      selected:
        type: boolean
        description: Defines if the extra ingredient will be added or not the ExtraDish.
  ReservationView:
    type: object
    properties:
      event:
        type: object
        $ref: "#/definitions/Event"
      email:
        type: string
        description: The email of the user that has set up the Reservation.
      adults:
        type: integer
        description: The number of adults that are attending.
      kids:
        type: integer
        description: The number of kids that are attending.
  InvitationView:
    type: object
    properties:
      event:
        type: object
        $ref: "#/definitions/Event"
      nameOwner:
        type: string
        description: The name of the user that sent the Invitation.
      emailOwner:
        type: string
        description: The emial of the user that sent the Invitation.
      friends:
        type: array
        description: All the emails the Invitation is sent to.
        items:
          type: string
      invitationNumber:
        type: integer
        description: Identifier of the Invitation
  Event:
    type: object
    properties:
      date:
        type: string
        description: the date (month/day/year) when the Event is happening.
      hour:
        type: string
        description: The Date's time when the Event is happening.
      name:
        type: string
        description: The name of the Event.
  Filter:
    type: object
    properties:
      main:
        type: boolean
        description: TODO
      starter:
        type: boolean
        description: TODO
      dessert:
        type: boolean
        description: TODO
      noodle:
        type: boolean
        description: TODO
      rice:
        type: boolean
        description: TODO
      curry:
        type: boolean
        description: TODO
      vegan:
        type: boolean
        description: TODO
      vegetarian:
        type: boolean
        description: TODO
      favourites:
        type: boolean
        description: TODO
      price:
        type: number
        description: TODO
      likes:
        type: integer
        description: TODO
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
